version: '3.8'

services:
  db:
    image: postgres:15
    container_name: measurements-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: measurements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: measurements-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: measurements
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: